/* ===== БАЗА ПРОДУКТОВ (источник истины) =====
   Можно править вручную: КБЖУ (k,p,f,cb на 100 г), добавлять/удалять объекты.
   id — уникальный код (латиницей). После правки сохрани файл и перезагрузи страницы.
   Конструктор, CRUD и меню читают этот файл. Правки из CRUD-страницы хранятся
   поверх (localStorage) и применяются сразу; «Экспорт» вернёт их в этот файл.
   Поля: id, n(название), c(категория), k,p,f,cb /100г, d(дефолт г),
         pack(г в упаковке), pl(подпись упаковки), tags[], url. */

const KD_MEALS = ["До трен.","Завтрак","Обед","Перекус","Ужин","Протеин","Вкусняшка"];
const KD_CATORD = ["Белок","Гарнир/углеводы","Безлактозное","Готовое","Овощи","Фрукты","Соусы/жиры","Вкусняшки"];
const KD_CATCOL = {"Белок":"#2f6fed","Гарнир/углеводы":"#16a34a","Безлактозное":"#0ea5a8","Готовое":"#7c3aed","Овощи":"#65a30d","Фрукты":"#db2777","Соусы/жиры":"#e0a106","Вкусняшки":"#b5179e"};
const KD_TAGB = {bloat:["вздутие","b-bloat"],fat:["жирное","b-fat"],trn:["вокруг трен.","b-trn"]};

// Цели: тренировочный день (больше углеводов вокруг зала) и день отдыха
const KD_TARGETS = {
  train: { k:[2400,2550,2450], p:[140,160,150], f:[60,80,72], c:[300,335,315] },
  rest:  { k:[2300,2450,2350], p:[140,160,150], f:[60,80,72], c:[270,305,285] }
};

const KD_PRODUCTS_BASE = [
{
"id": "kotleti_indeika",
"n": "Котлеты индейки диетические",
"c": "Белок",
"k": 160,
"p": 16,
"f": 10,
"cb": 1,
"d": 100,
"pack": 300,
"pl": "уп. 300 г",
"tags": [],
"url": "https://vkusvill.ru/goods/kotlety-iz-indeyki-dieticheskie-38076.html"
},
{
"id": "kotleti_ik",
"n": "Котлеты индейка-кролик",
"c": "Белок",
"k": 150,
"p": 16,
"f": 9,
"cb": 1,
"d": 100,
"pack": 300,
"pl": "уп. 300 г",
"tags": [],
"url": ""
},
{
"id": "tefteli",
"n": "Тефтели индейки",
"c": "Белок",
"k": 150,
"p": 15,
"f": 9,
"cb": 3,
"d": 100,
"pack": 300,
"pl": "уп. 300 г",
"tags": [],
"url": ""
},
{
"id": "farsh_indeika",
"n": "Фарш индейки",
"c": "Белок",
"k": 110,
"p": 20,
"f": 3,
"cb": 0,
"d": 120,
"pack": 400,
"pl": "уп. 400 г",
"tags": [],
"url": ""
},
{
"id": "file_indeika",
"n": "Филе индейки (грудка)",
"c": "Белок",
"k": 110,
"p": 22,
"f": 2,
"cb": 0,
"d": 120,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": ""
},
{
"id": "bedro_indeika",
"n": "Бедро индейки без кожи",
"c": "Белок",
"k": 130,
"p": 18,
"f": 6,
"cb": 0,
"d": 120,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": ""
},
{
"id": "bedro_kura",
"n": "Бедро курицы без кожи",
"c": "Белок",
"k": 150,
"p": 18,
"f": 9,
"cb": 0,
"d": 120,
"pack": 750,
"pl": "уп. 750 г",
"tags": [],
"url": "https://vkusvill.ru/goods/file-bedra-kurinoe-beskostnoe-750-g-67172.html"
},
{
"id": "golen_kura",
"n": "Голень курицы без кожи",
"c": "Белок",
"k": 150,
"p": 17,
"f": 9,
"cb": 0,
"d": 120,
"pack": 600,
"pl": "уп. ~600 г",
"tags": [],
"url": ""
},
{
"id": "govjadina_tush",
"n": "Говядина тушёная",
"c": "Белок",
"k": 180,
"p": 25,
"f": 9,
"cb": 0,
"d": 120,
"pack": 325,
"pl": "банка ~325 г",
"tags": [],
"url": "https://vkusvill.ru/goods/govyadina-tushenaya-19493.html"
},
{
"id": "scheki",
"n": "Говяжьи щёчки тушёные",
"c": "Белок",
"k": 200,
"p": 22,
"f": 12,
"cb": 0,
"d": 120,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [
"fat"
],
"url": ""
},
{
"id": "vetchina_indeika",
"n": "Ветчина из индейки",
"c": "Белок",
"k": 100,
"p": 16,
"f": 3,
"cb": 1,
"d": 80,
"pack": 200,
"pl": "уп. 200 г",
"tags": [],
"url": ""
},
{
"id": "pechen_kura",
"n": "Печень куриная (без сметаны)",
"c": "Белок",
"k": 140,
"p": 20,
"f": 6,
"cb": 1,
"d": 120,
"pack": 400,
"pl": "уп. ~400 г",
"tags": [],
"url": ""
},
{
"id": "yaico",
"n": "Яйцо куриное",
"c": "Белок",
"k": 150,
"p": 13,
"f": 11,
"cb": 1,
"d": 110,
"pack": 550,
"pl": "10 шт",
"tags": [],
"url": "https://vkusvill.ru/search/?q=%D1%8F%D0%B9%D1%86%D0%BE",
"gpp": 55
},
{
"id": "belki",
"n": "Яичные белки (1 белок ~33 г)",
"gpp": 33,
"c": "Белок",
"k": 50,
"p": 11,
"f": 0,
"cb": 1,
"d": 150,
"pack": 500,
"pl": "уп. 500 г",
"tags": [],
"url": ""
},
{
"id": "hek",
"n": "Хек",
"c": "Белок",
"k": 82,
"p": 16.5,
"f": 1.8,
"cb": 0,
"d": 150,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": "https://vkusvill.ru/goods/ryba-ikra-i-moreprodukty/"
},
{
"id": "treska",
"n": "Треска",
"c": "Белок",
"k": 78,
"p": 18,
"f": 0.7,
"cb": 0,
"d": 150,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": "https://vkusvill.ru/goods/ryba-ikra-i-moreprodukty/"
},
{
"id": "mintai",
"n": "Минтай",
"c": "Белок",
"k": 80,
"p": 17,
"f": 1,
"cb": 0,
"d": 150,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": "https://vkusvill.ru/goods/ryba-ikra-i-moreprodukty/mintay/"
},
{
"id": "piksha",
"n": "Пикша",
"c": "Белок",
"k": 90,
"p": 19,
"f": 0.5,
"cb": 0,
"d": 150,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": ""
},
{
"id": "forel",
"n": "Форель / лосось",
"c": "Белок",
"k": 170,
"p": 20,
"f": 8,
"cb": 0,
"d": 100,
"pack": 500,
"pl": "уп. 500 г",
"tags": [
"fat"
],
"url": "https://vkusvill.ru/goods/forel-raduzhnaya-steyk-zam-500-g-70541.html"
},
{
"id": "tunec",
"n": "Тунец в собств. соку",
"c": "Белок",
"k": 100,
"p": 23,
"f": 1,
"cb": 0,
"d": 100,
"pack": 150,
"pl": "банка 150 г",
"tags": [],
"url": ""
},
{
"id": "krevetki",
"n": "Креветки",
"c": "Белок",
"k": 90,
"p": 19,
"f": 1,
"cb": 1,
"d": 120,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": ""
},
{
"id": "kalmar",
"n": "Кальмар",
"c": "Белок",
"k": 90,
"p": 18,
"f": 2,
"cb": 2,
"d": 120,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": ""
},
{
"id": "midii",
"n": "Мидии",
"c": "Белок",
"k": 80,
"p": 12,
"f": 2,
"cb": 3,
"d": 150,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": "https://vkusvill.ru/search/?q=%D0%BC%D0%B8%D0%B4%D0%B8%D0%B8"
},
{
"id": "ryb_kotleti_gotov",
"n": "Рыбные котлеты минтай (готовое)",
"c": "Готовое",
"k": 150,
"p": 13,
"f": 8,
"cb": 8,
"d": 150,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": "https://vkusvill.ru/goods/gotovaya-eda/vtorye-blyuda/"
},
{
"id": "indeika_gril_gotov",
"n": "Филе индейки гриль с гарниром (готовое)",
"c": "Готовое",
"k": 130,
"p": 12,
"f": 4,
"cb": 12,
"d": 250,
"pack": 250,
"pl": "порция 250 г",
"tags": [],
"url": "https://vkusvill.ru/goods/gotovaya-eda/vtorye-blyuda/"
},
{
"id": "smuzi",
"n": "Смузи-гейнер (протеин+банан+овсянка+мёд+раст.молоко)",
"c": "Готовое",
"k": 116,
"p": 7.6,
"f": 2.2,
"cb": 17.5,
"d": 455,
"pack": 455,
"pl": "1 порция (блендер)",
"tags": [
"trn"
],
"url": ""
},
{
"id": "smuzi_base",
"n": "Смузи-база (протеин+банан+овсянка+раст.молоко, без подсластителя)",
"c": "Готовое",
"k": 106,
"p": 7.6,
"f": 2.2,
"cb": 14.8,
"d": 455,
"pack": 455,
"pl": "1 порция (блендер)",
"tags": [
"trn"
],
"url": ""
},
{
"id": "whey",
"n": "Whey isolate (порошок)",
"c": "Белок",
"k": 370,
"p": 85,
"f": 3,
"cb": 4,
"d": 30,
"pack": 900,
"pl": "банка ~900 г",
"tags": [
"trn"
],
"url": ""
},
{
"id": "bezlakt_tvorog",
"n": "Безлактозный творог",
"c": "Безлактозное",
"k": 100,
"p": 16,
"f": 2,
"cb": 3,
"d": 150,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": "https://vkusvill.ru/goods/molochnye-produkty-yaytso/bezlaktoznye-produkty/"
},
{
"id": "bezlakt_yogurt",
"n": "Безлактозный йогурт высокобелк.",
"c": "Безлактозное",
"k": 70,
"p": 9,
"f": 2,
"cb": 4,
"d": 125,
"pack": 125,
"pl": "стакан 125 г",
"tags": [],
"url": "https://vkusvill.ru/goods/molochnye-produkty-yaytso/bezlaktoznye-produkty/",
"gpp": 125
},
{
"id": "bezlakt_kefir",
"n": "Безлактозный кефир",
"c": "Безлактозное",
"k": 40,
"p": 3,
"f": 1,
"cb": 4,
"d": 200,
"pack": 500,
"pl": "бутылка ~500 мл",
"tags": [],
"url": "https://vkusvill.ru/goods/molochnye-produkty-yaytso/bezlaktoznye-produkty/"
},
{
"id": "bezlakt_moloko",
"n": "Безлактозное молоко",
"c": "Безлактозное",
"k": 45,
"p": 3,
"f": 1.5,
"cb": 5,
"d": 200,
"pack": 970,
"pl": "970 мл",
"tags": [],
"url": "https://vkusvill.ru/goods/moloko-bezlaktoznoe-ultrapasterizovannoe-3-2-970-ml-94473.html"
},
{
"id": "rast_moloko",
"n": "Растительное молоко (овсяное/кокосовое)",
"c": "Безлактозное",
"k": 45,
"p": 1,
"f": 2.5,
"cb": 6,
"d": 250,
"pack": 1000,
"pl": "1 л",
"tags": [],
"url": "https://vkusvill.ru/search/?q=%D1%80%D0%B0%D1%81%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5+%D0%BC%D0%BE%D0%BB%D0%BE%D0%BA%D0%BE"
},
{
"id": "ris",
"n": "Рис (СУХОЙ вес)",
"c": "Гарнир/углеводы",
"k": 350,
"p": 7,
"f": 1,
"cb": 78,
"d": 100,
"pack": 800,
"pl": "уп. ~800 г",
"tags": [
"trn"
],
"url": "https://vkusvill.ru/goods/krupy-makarony-muka/krupy/"
},
{
"id": "grechka",
"n": "Гречка (СУХОЙ вес)",
"c": "Гарнир/углеводы",
"k": 340,
"p": 12.6,
"f": 3.3,
"cb": 62,
"d": 100,
"pack": 800,
"pl": "уп. ~800 г",
"tags": [],
"url": "https://vkusvill.ru/goods/krupy-makarony-muka/krupy/"
},
{
"id": "ovsjanka",
"n": "Овсянка Геркулес (СУХОЙ)",
"c": "Гарнир/углеводы",
"k": 360,
"p": 12,
"f": 6.5,
"cb": 62,
"d": 60,
"pack": 400,
"pl": "уп. 400 г",
"tags": [],
"url": "https://vkusvill.ru/goods/gerkules-ovsyanye-khlopya-400-g-1248.html"
},
{
"id": "makaroni",
"n": "Макароны без глютена (рис/кукуруза, СУХИЕ)",
"c": "Гарнир/углеводы",
"k": 350,
"p": 7,
"f": 1.5,
"cb": 77,
"d": 90,
"pack": 400,
"pl": "уп. ~400 г",
"tags": [],
"url": "https://vkusvill.ru/search/?q=%D0%BC%D0%B0%D0%BA%D0%B0%D1%80%D0%BE%D0%BD%D1%8B+%D0%B1%D0%B5%D0%B7+%D0%B3%D0%BB%D1%8E%D1%82%D0%B5%D0%BD%D0%B0"
},
{
"id": "bulgur",
"n": "Булгур (СУХОЙ)",
"c": "Гарнир/углеводы",
"k": 340,
"p": 12,
"f": 1.5,
"cb": 63,
"d": 80,
"pack": 350,
"pl": "уп. ~350 г",
"tags": [],
"url": ""
},
{
"id": "kinoa",
"n": "Киноа (СУХАЯ)",
"c": "Гарнир/углеводы",
"k": 368,
"p": 14,
"f": 6,
"cb": 57,
"d": 70,
"pack": 350,
"pl": "уп. ~350 г",
"tags": [],
"url": ""
},
{
"id": "psheno",
"n": "Пшено (СУХОЕ)",
"c": "Гарнир/углеводы",
"k": 348,
"p": 11,
"f": 3.3,
"cb": 66,
"d": 80,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": ""
},
{
"id": "kartofel",
"n": "Картофель (в мундире)",
"c": "Гарнир/углеводы",
"k": 77,
"p": 2,
"f": 0.4,
"cb": 17,
"d": 330,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": "https://vkusvill.ru/search/?q=%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%84%D0%B5%D0%BB%D1%8C"
},
{
"id": "batat",
"n": "Батат",
"c": "Гарнир/углеводы",
"k": 86,
"p": 1.6,
"f": 0.1,
"cb": 20,
"d": 250,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": ""
},
{
"id": "lavash",
"n": "Лаваш армянский",
"c": "Гарнир/углеводы",
"k": 236,
"p": 8,
"f": 1.5,
"cb": 50,
"d": 40,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [
"trn"
],
"url": "https://vkusvill.ru/goods/lavash-armyanskiy-po-derevenski-220-g-18161.html"
},
{
"id": "ris_hlebcy",
"n": "Рисовые хлебцы",
"c": "Гарнир/углеводы",
"k": 380,
"p": 8,
"f": 3,
"cb": 80,
"d": 20,
"pack": 100,
"pl": "уп. ~100 г",
"tags": [
"trn"
],
"url": ""
},
{
"id": "hleb_cz",
"n": "Хлеб цельнозерновой",
"c": "Гарнир/углеводы",
"k": 230,
"p": 9,
"f": 3,
"cb": 43,
"d": 60,
"pack": 300,
"pl": "буханка ~300 г",
"tags": [],
"url": ""
},
{
"id": "kuskus",
"n": "Кускус (СУХОЙ)",
"c": "Гарнир/углеводы",
"k": 350,
"p": 12,
"f": 1,
"cb": 72,
"d": 70,
"pack": 500,
"pl": "уп. ~500 г",
"tags": [],
"url": ""
},
{
"id": "polenta",
"n": "Полента / кукурузная крупа (СУХАЯ, б/глют.)",
"c": "Гарнир/углеводы",
"k": 330,
"p": 8,
"f": 1.5,
"cb": 72,
"d": 80,
"pack": 400,
"pl": "уп. ~400 г",
"tags": [],
"url": "https://vkusvill.ru/search/?q=%D0%BA%D1%83%D0%BA%D1%83%D1%80%D1%83%D0%B7%D0%BD%D0%B0%D1%8F+%D0%BA%D1%80%D1%83%D0%BF%D0%B0"
},
{
"id": "kukur_tortilla",
"n": "Кукурузная тортилья (б/глют.)",
"c": "Гарнир/углеводы",
"k": 320,
"p": 8,
"f": 4,
"cb": 64,
"d": 60,
"pack": 240,
"pl": "уп. ~6 шт",
"tags": [
"trn"
],
"url": "https://vkusvill.ru/search/?q=%D1%82%D0%BE%D1%80%D1%82%D0%B8%D0%BB%D1%8C%D1%8F",
"gpp": 40
},
{
"id": "ogurec",
"n": "Огурец",
"c": "Овощи",
"k": 14,
"p": 0.8,
"f": 0.1,
"cb": 3,
"d": 150,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": ""
},
{
"id": "kabachok",
"n": "Кабачок",
"c": "Овощи",
"k": 20,
"p": 1,
"f": 0.3,
"cb": 4,
"d": 150,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": ""
},
{
"id": "morkov",
"n": "Морковь",
"c": "Овощи",
"k": 35,
"p": 1,
"f": 0.2,
"cb": 8,
"d": 100,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": ""
},
{
"id": "pomidor",
"n": "Помидор",
"c": "Овощи",
"k": 18,
"p": 0.9,
"f": 0.2,
"cb": 4,
"d": 150,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": ""
},
{
"id": "tush_ovoschi",
"n": "Тушёные овощи (кабачок-морковь)",
"c": "Овощи",
"k": 45,
"p": 1.2,
"f": 2,
"cb": 5,
"d": 150,
"pack": 1000,
"pl": "~1 кг смеси",
"tags": [],
"url": ""
},
{
"id": "brokkoli",
"n": "Брокколи",
"c": "Овощи",
"k": 34,
"p": 2.8,
"f": 0.4,
"cb": 7,
"d": 150,
"pack": 400,
"pl": "уп. ~400 г",
"tags": [
"bloat"
],
"url": ""
},
{
"id": "cvetnaya",
"n": "Цветная капуста",
"c": "Овощи",
"k": 30,
"p": 2.5,
"f": 0.3,
"cb": 5,
"d": 150,
"pack": 400,
"pl": "уп. ~400 г",
"tags": [
"bloat"
],
"url": ""
},
{
"id": "tykva",
"n": "Тыква",
"c": "Овощи",
"k": 25,
"p": 1,
"f": 0.1,
"cb": 6,
"d": 150,
"pack": 1000,
"pl": "~1 кг",
"tags": [],
"url": "https://vkusvill.ru/goods/tykva-kroshka-16394.html"
},
{
"id": "shpinat",
"n": "Шпинат",
"c": "Овощи",
"k": 23,
"p": 2.9,
"f": 0.4,
"cb": 4,
"d": 100,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [],
"url": ""
},
{
"id": "goroshek",
"n": "Зелёный горошек",
"c": "Овощи",
"k": 80,
"p": 5,
"f": 0.4,
"cb": 14,
"d": 80,
"pack": 400,
"pl": "банка/уп. ~400 г",
"tags": [
"bloat"
],
"url": ""
},
{
"id": "fasol_struch",
"n": "Стручковая фасоль (заморозка ВВ, 400 г)",
"c": "Овощи",
"k": 31,
"p": 2,
"f": 0.2,
"cb": 5,
"d": 150,
"pack": 400,
"pl": "уп. ~400 г",
"tags": [],
"url": "https://vkusvill.ru/goods/fasol-struchkovaya-16091/"
},
{
"id": "ovoschi_gril_zam",
"n": "Смесь «Овощи гриль» зам. (кабачок-баклажан-перец)",
"c": "Овощи",
"k": 44,
"p": 1.3,
"f": 2.2,
"cb": 4.5,
"d": 80,
"pack": 400,
"pl": "уп. 400 г",
"tags": [],
"url": "https://vkusvill.ru/goods/smes-ovoshchi-gril-bystrozamorozhennaya-44519.html"
},
{
"id": "baklazhan",
"n": "Баклажан (запечь/гриль)",
"c": "Овощи",
"k": 24,
"p": 1.2,
"f": 0.1,
"cb": 4.5,
"d": 80,
"pack": 0,
"pl": "на развес",
"tags": [],
"url": ""
},
{
"id": "tykva_zapech",
"n": "Тыква запечённая с базиликом (готовая ВВ, КБЖУ уточнить на уп.)",
"c": "Готовое",
"k": 72,
"p": 1.1,
"f": 3.5,
"cb": 9,
"d": 80,
"pack": 150,
"pl": "уп. 150 г",
"tags": [],
"url": "https://vkusvill.ru/goods/tykva-zapechennaya-s-bazilikom-150-g-107334.html"
},
{
"id": "banan",
"n": "Банан",
"c": "Фрукты",
"k": 95,
"p": 1.3,
"f": 0.3,
"cb": 22,
"d": 120,
"pack": 120,
"pl": "1 шт",
"tags": [
"trn"
],
"url": "",
"gpp": 120
},
{
"id": "kivi",
"n": "Киви",
"c": "Фрукты",
"k": 48,
"p": 0.9,
"f": 0.5,
"cb": 11,
"d": 75,
"pack": 75,
"pl": "1 шт",
"tags": [
"bloat"
],
"url": "",
"gpp": 75
},
{
"id": "klubnika",
"n": "Клубника",
"c": "Фрукты",
"k": 33,
"p": 0.7,
"f": 0.4,
"cb": 7,
"d": 100,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": ""
},
{
"id": "yabloko",
"n": "Яблоко",
"c": "Фрукты",
"k": 52,
"p": 0.3,
"f": 0.2,
"cb": 14,
"d": 150,
"pack": 150,
"pl": "1 шт",
"tags": [
"bloat"
],
"url": "",
"gpp": 150
},
{
"id": "apelsin",
"n": "Апельсин",
"c": "Фрукты",
"k": 47,
"p": 0.9,
"f": 0.1,
"cb": 12,
"d": 130,
"pack": 130,
"pl": "1 шт",
"tags": [],
"url": "",
"gpp": 130
},
{
"id": "grusha",
"n": "Груша",
"c": "Фрукты",
"k": 57,
"p": 0.4,
"f": 0.1,
"cb": 15,
"d": 150,
"pack": 150,
"pl": "1 шт",
"tags": [
"bloat"
],
"url": "",
"gpp": 150
},
{
"id": "yagody",
"n": "Ягоды (черника/смородина)",
"c": "Фрукты",
"k": 44,
"p": 0.7,
"f": 0.3,
"cb": 10,
"d": 100,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [],
"url": ""
},
{
"id": "oil",
"n": "Оливковое масло",
"c": "Соусы/жиры",
"k": 900,
"p": 0,
"f": 100,
"cb": 0,
"d": 10,
"pack": 500,
"pl": "500 мл",
"tags": [
"fat"
],
"url": "https://vkusvill.ru/goods/maslo-olivkovoe-extra-virgin-1213.html"
},
{
"id": "tomat_sous",
"n": "Томатный соус / пассата",
"c": "Соусы/жиры",
"k": 30,
"p": 1.5,
"f": 0.3,
"cb": 6,
"d": 40,
"pack": 350,
"pl": "уп. ~350 г",
"tags": [],
"url": ""
},
{
"id": "lecho",
"n": "Лечо",
"c": "Соусы/жиры",
"k": 40,
"p": 1,
"f": 1,
"cb": 7,
"d": 50,
"pack": 500,
"pl": "банка ~500 г",
"tags": [],
"url": ""
},
{
"id": "soevy",
"n": "Соевый соус",
"c": "Соусы/жиры",
"k": 60,
"p": 6,
"f": 0,
"cb": 6,
"d": 15,
"pack": 200,
"pl": "~200 мл",
"tags": [],
"url": ""
},
{
"id": "adjika",
"n": "Аджика",
"c": "Соусы/жиры",
"k": 40,
"p": 1,
"f": 1,
"cb": 8,
"d": 20,
"pack": 300,
"pl": "банка ~300 г",
"tags": [],
"url": ""
},
{
"id": "gorchica",
"n": "Горчица",
"c": "Соусы/жиры",
"k": 95,
"p": 5,
"f": 4,
"cb": 6,
"d": 15,
"pack": 200,
"pl": "~200 г",
"tags": [],
"url": ""
},
{
"id": "bulon",
"n": "Бульон (куриный/говяжий)",
"c": "Соусы/жиры",
"k": 15,
"p": 2,
"f": 0.5,
"cb": 1,
"d": 150,
"pack": 500,
"pl": "~500 мл",
"tags": [],
"url": ""
},
{
"id": "salsa",
"n": "Сальса томатная",
"c": "Соусы/жиры",
"k": 35,
"p": 1,
"f": 0.2,
"cb": 7,
"d": 40,
"pack": 300,
"pl": "банка ~300 г",
"tags": [],
"url": ""
},
{
"id": "med",
"n": "Мёд",
"c": "Соусы/жиры",
"k": 320,
"p": 0.3,
"f": 0,
"cb": 82,
"d": 15,
"pack": 250,
"pl": "банка ~250 г",
"tags": [
"trn"
],
"url": ""
},
{
"id": "avokado",
"n": "Авокадо",
"c": "Соусы/жиры",
"k": 160,
"p": 2,
"f": 15,
"cb": 2,
"d": 70,
"pack": 200,
"pl": "1 шт ~200 г",
"tags": [
"fat"
],
"url": "",
"gpp": 200
},
{
"id": "kakao",
"n": "Какао порошок",
"c": "Соусы/жиры",
"k": 350,
"p": 20,
"f": 14,
"cb": 15,
"d": 10,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [],
"url": ""
},
{
"id": "mango",
"n": "Манго",
"c": "Фрукты",
"k": 60,
"p": 0.8,
"f": 0.4,
"cb": 15,
"d": 100,
"pack": 300,
"pl": "~300 г",
"tags": [],
"url": ""
},
{
"id": "arah_pasta",
"n": "Арахисовая паста (натуральная)",
"c": "Соусы/жиры",
"k": 600,
"p": 25,
"f": 50,
"cb": 15,
"d": 15,
"pack": 300,
"pl": "банка ~300 г",
"tags": [
"fat"
],
"url": ""
},
{
"id": "zefir",
"n": "Зефир",
"c": "Вкусняшки",
"k": 320,
"p": 1,
"f": 0,
"cb": 79,
"d": 30,
"pack": 250,
"pl": "уп. ~250 г",
"tags": [],
"url": "https://vkusvill.ru/goods/sladosti-i-deserty/zefir-pastila-beze-i-marmelad/",
"gpp": 15
},
{
"id": "pastila",
"n": "Пастила белёвская",
"c": "Вкусняшки",
"k": 320,
"p": 0.5,
"f": 0,
"cb": 78,
"d": 30,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [],
"url": "https://vkusvill.ru/goods/sladosti-i-deserty/zefir-pastila-beze-i-marmelad/"
},
{
"id": "marmelad",
"n": "Мармелад",
"c": "Вкусняшки",
"k": 320,
"p": 0,
"f": 0,
"cb": 79,
"d": 30,
"pack": 250,
"pl": "уп. ~250 г",
"tags": [],
"url": "https://vkusvill.ru/goods/sladosti-i-deserty/zefir-pastila-beze-i-marmelad/"
},
{
"id": "shokolad",
"n": "Горький шоколад 70%+",
"c": "Вкусняшки",
"k": 550,
"p": 8,
"f": 35,
"cb": 45,
"d": 15,
"pack": 90,
"pl": "плитка ~90 г",
"tags": [
"fat"
],
"url": ""
},
{
"id": "sorbet",
"n": "Фруктовый сорбет",
"c": "Вкусняшки",
"k": 130,
"p": 0,
"f": 0,
"cb": 32,
"d": 80,
"pack": 80,
"pl": "стакан ~80 г",
"tags": [],
"url": "https://vkusvill.ru/goods/osoboe-pitanie/produkty-bez-laktozy/morozhenoe-bez-laktozy/"
},
{
"id": "morozh_bezlakt",
"n": "Мороженое без лактозы",
"c": "Вкусняшки",
"k": 170,
"p": 3,
"f": 6,
"cb": 26,
"d": 70,
"pack": 70,
"pl": "стакан ~70 г",
"tags": [],
"url": "https://vkusvill.ru/goods/osoboe-pitanie/produkty-bez-laktozy/morozhenoe-bez-laktozy/"
},
{
"id": "finiki",
"n": "Финики",
"c": "Вкусняшки",
"k": 306,
"p": 1.8,
"f": 0,
"cb": 75,
"d": 25,
"pack": 300,
"pl": "уп. ~300 г",
"tags": [
"trn"
],
"url": "https://vkusvill.ru/goods/finiki-semushka-korolevskie-300-g-62773.html",
"gpp": 8
},
{
"id": "izyum",
"n": "Изюм",
"c": "Вкусняшки",
"k": 300,
"p": 3,
"f": 0.5,
"cb": 79,
"d": 30,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [
"bloat",
"trn"
],
"url": ""
},
{
"id": "chernosliv",
"n": "Чернослив",
"c": "Вкусняшки",
"k": 240,
"p": 2,
"f": 0.4,
"cb": 57,
"d": 30,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [
"bloat"
],
"url": ""
},
{
"id": "kuraga",
"n": "Курага",
"c": "Вкусняшки",
"k": 240,
"p": 3,
"f": 0.5,
"cb": 55,
"d": 30,
"pack": 200,
"pl": "уп. ~200 г",
"tags": [
"bloat"
],
"url": ""
},
{
"id": "varenje",
"n": "Варенье / джем",
"c": "Вкусняшки",
"k": 250,
"p": 0.3,
"f": 0,
"cb": 62,
"d": 20,
"pack": 300,
"pl": "банка ~300 г",
"tags": [],
"url": ""
},
{
"id": "funduk",
"n": "Фундук",
"c": "Вкусняшки",
"k": 650,
"p": 15,
"f": 61,
"cb": 9,
"d": 25,
"pack": 150,
"pl": "уп. 150 г",
"tags": [],
"url": ""
},
{
"id": "pekan",
"n": "Пекан",
"c": "Вкусняшки",
"k": 690,
"p": 9,
"f": 72,
"cb": 14,
"d": 20,
"pack": 100,
"pl": "уп. 100 г",
"tags": [],
"url": ""
},
{
"id": "orehi_mix",
"n": "Ореховый микс (миндаль+грецкий+фундук 1:1:1)",
"c": "Вкусняшки",
"k": 633,
"p": 17,
"f": 60,
"cb": 11,
"d": 25,
"pack": 450,
"pl": "банка-микс (3 уп. по 150 г)",
"tags": [],
"url": ""
},
{
"id": "mindal",
"n": "Миндаль",
"c": "Вкусняшки",
"k": 600,
"p": 21,
"f": 53,
"cb": 13,
"d": 20,
"pack": 150,
"pl": "уп. ~150 г",
"tags": [
"fat"
],
"url": ""
},
{
"id": "greckiy",
"n": "Грецкий орех",
"c": "Вкусняшки",
"k": 650,
"p": 15,
"f": 65,
"cb": 11,
"d": 20,
"pack": 150,
"pl": "уп. ~150 г",
"tags": [
"fat"
],
"url": ""
}
];

// поиск-ссылка ВкусВилл как фолбэк, если у продукта нет url
function kdUrl(p){ return p.url && p.url.length ? p.url
  : "https://vkusvill.ru/search/?q=" + encodeURIComponent(p.n.replace(/\s*\(.*?\)/g,'').trim()); }

// эффективный список = база + правки из CRUD (localStorage)
function kdGetProducts(){
  try{ const full=JSON.parse(localStorage.getItem('kd_products_full')||'null'); if(full&&full.length) return full.map(x=>Object.assign({},x)); }catch(e){}
  let base = KD_PRODUCTS_BASE.map(x=>Object.assign({},x));
  let ov; try{ ov = JSON.parse(localStorage.getItem('kd_overrides')||'null'); }catch(e){ ov=null; }
  if(!ov) return base;
  let map = {}; base.forEach(p=>map[p.id]=p);
  (ov.deleted||[]).forEach(id=>{ delete map[id]; });
  Object.entries(ov.edited||{}).forEach(([id,patch])=>{ if(map[id]) Object.assign(map[id],patch); });
  let list = Object.values(map);
  (ov.added||[]).forEach(p=>list.push(Object.assign({},p)));
  return list;
}
// округление граммов до целых упаковок
function kdPacks(grams,p){
  const pack = p.pack||grams||1;
  const n = Math.max(1, Math.ceil(grams/pack));
  return { units:n, label:p.pl||(pack+" г"), totalPack:n*pack };
}
